sudo: required
dist: trusty
language: node_js
addons:
  apt:
    packages:
      - pulseaudio
node_js:
- '4'

env:
  matrix:
    - BROWSER=chrome  BVER=stable
    - BROWSER=firefox BVER=stable
    - BROWSER=chrome  BVER=beta
    - BROWSER=chrome  BVER=unstable
    - BROWSER=firefox BVER=unstable
    - os: osx
      osx_image: xcode9
      env: BROWSER=safari BVER=unstable

  global:
  - TRAVIS=true
  - UNIT_CMD='npm run unit'
  - INTEGRATION_CMD=''
  - OT_API_KEY='44935341'
  - OT_SESSION_ID='1_MX40NDkzNTM0MX5-MTQ2ODgwODY2NjQxOH56NWdGQk9OSi9wKyt5YVpqbDJUTnZOV2Z-fg'
  - ENCRYPTION_LABEL='32ad1f65cbbe'
  - COMMIT_AUTHOR_EMAIL='adam@tokbox.com'

matrix:
  fast_finish: true
  allow_failures:
    - env: BROWSER=firefox BVER=unstable
    - env: BROWSER=chrome  BVER=unstable


before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - pulseaudio --start

after_success:
  - ./deploy.sh
