sudo: false
language: node_js
node_js:
- '4'

env:
  matrix:
    - BROWSER=chrome  BVER=stable
    - BROWSER=firefox BVER=unstable

  global:
  - TRAVIS=true
  - UNIT_CMD='npm run unit'
  - INTEGRATION_CMD=''

matrix:
  fast_finish: true

before_script:
  - ./node_modules/travis-multirunner/setup.sh
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
